### ISSUE TITLE
Add support for Chrome on IOS devices

### ISSUE THREAD

**Issue by MykolaShevchuk** [Joe12387/detectIncognito#10]
Currently, detect-incognito is not detecting Chrome incognito on IOS devices. Do you have some ideas on how to achieve this?

**Comment by Joe12387** [comment]
Yes, I have a fix for this. Will implement within the next 24 to 48 hours.

**Comment by Joe12387** [comment]
A preliminary Safari method has been added to detectIncognito.js. Changes are not yet reflected in detectIncognito.min.js nor in TypeScript. If anyone wants to update the TypeScript, feel free to submit a pull request.

**Comment by MykolaShevchuk** [comment]
@Joe12387 thank you! I've tested your update and now it works correctly.
