### ISSUE TITLE
detectIncognito v1.1.2 exports is not defined     at detectIncognito.min.js:6:36

### ISSUE THREAD

**Issue by alex-granovskiy** [Joe12387/detectIncognito#16]
detectIncognito v1.1.2
Console:
detectIncognito.min.js:6 Uncaught ReferenceError: exports is not defined
    at detectIncognito.min.js:6:36
(anonymous) @ detectIncognito.min.js:6

https://cdn.jsdelivr.net/gh/Joe12387/detectIncognito\@main/detectIncognito.min.js

**Comment by p810** [comment]
Opened a PR for a potential solution here: #17 

Feedback would be appreciated!
