### ISSUE TITLE
chrome/v8 106+ support

### ISSUE THREAD

**Issue by wololodev** [Joe12387/detectIncognito#19]
106's update comes with jsHeapSizeLimit matching incongnito and normal browsing. Arms race continues.. I will update if I find a new way... any ideas are welcome

**Comment by Joe12387** [comment]
I'm unable to replicate this on v106 on macOS. Does detectincognito.com work for you?

**Comment by wololodev** [comment]
it's 50/50 actually - just had a bad roll when i put up the issue 
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/1749207/197366635-4fe65d0d-36f5-476f-8b09-fe2662f42730.png">

is it always consistent for you?

**Comment by Joe12387** [comment]
For me it's consistent. Perhaps an extension is causing some interference?

**Comment by Joe12387** [comment]
Cannot reproduce.
