### ISSUE TITLE
Always returning true on Chrome 95.0.4638.69 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by gabycperezdias** [Joe12387/detectIncognito#2]
Checking on console, `jsHeapSizeLimit` is exactly the same for both private and normal tabs

**Comment by Joe12387** [comment]
Hi.

I'm running Version 95.0.4638.69 (Official Build) (x86_64) on macOS and I am unable to reproduce the error. 

I have some questions, if you would:
1. Does detectincognito.com provide an accurate reading, or are you getting false results there too?
2. Are you running any extensions? If so, disable all of them and restart Chrome to see if the error persists.
3. What OS are you running?
4. Can you reproduce the error on another device?

Thanks.

**Comment by gabycperezdias** [comment]
hummm funny enough detectincognito.com works.

1. Does detectincognito.com provide an accurate reading, or are you getting false results there too? **Accurate**
2. Are you running any extensions? If so, disable all of them and restart Chrome to see if the error persists. **No**
3. What OS are you running? **Windows**
4. Can you reproduce the error on another device? **Yes**

**Comment by Joe12387** [comment]
Are you running the script locally or remotely? If you're running it locally, it does seem to produce a false positive. I'll add that to the documentation.

**Comment by gabycperezdias** [comment]
![image](https://user-images.githubusercontent.com/6580266/141206248-e65bae1c-0be3-4dcb-9682-7f033113e3af.png)

But I see this...

**Comment by Joe12387** [comment]
jsHeapSizeLimit does not change between normal and incognito browsing. What does change between modes is the quota property that navigator.webkitTemporaryStorage.queryUsageAndQuota() spits out. If the quota is less than jsHeapSizeLimit, it's incognito.

**Comment by gabycperezdias** [comment]
ok, I will give it a try remotely

**Comment by Joe12387** [comment]
Happy to help!
