### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'iframe.contentWindow.applicationCache.addEventListener') on iOS 16 

### ISSUE THREAD

**Issue by qaynam** [Joe12387/detectIncognito#20]
## error

<img width="808" alt="image" src="https://user-images.githubusercontent.com/33139713/197951190-6e42a3c3-f46f-4b00-a203-fdf2217d43c5.png">

## code

```tsx
try {
    const result = await detectIncognito();

    if (result.isPrivate) {
      alert(
        'using private mode',
      );
      window.addEventListener('beforeunload', (e) => {
        e.preventDefault();
        e.returnValue =
          'using private mode';
      });
    }
  } catch (error) {
    console.error(error);
  }
```

## environment

safari 16 
iOS 16
iPhone 14 on Xcode simulator

## code base

ESbuild
react
typescript

---

btw awesome package ! work well on chrome and iOS 15

**Comment by Joe12387** [comment]
Hello! You appear to be using an old version of detectIncognito. Make sure you're using the new npm package name (detectincognitojs).

**Comment by qaynam** [comment]
ohh My bad , i was install wrong package.
fixed !! ✨
thx
