### ISSUE TITLE
new/easier safari method

### ISSUE THREAD

**Issue by jimmywarting** [Joe12387/detectIncognito#26]
```js
navigator.storage.getDirectory().then(ok => {
  console.log('not private')
}, err => {
  console.log('private')
})
```

**Comment by Joe12387** [comment]
Nice find! Elegant, too. Unfortunately, `navigator.storage.getDirectory()` is only supported by Safari 15.2, leaving a gap from Safari 13 to 15.2 with the current `newSafariTest()` method. Could be useful for when Apple inevitably nerfs the current method, though. Thanks!
