### ISSUE TITLE
Ublock Origin prevents loading of detectIncognito.js?

### ISSUE THREAD

**Issue by dcaud** [Joe12387/detectIncognito#35]
With the Ublock Origin Chrome plugin enabled, detectIncognito won't load on my machine. Any thoughts?

**Comment by amrgetment** [comment]
@dcaud by default extensions is not working in private mode except you allow it manually

**Comment by Joe12387** [comment]
detectIncognito is listed in "uBlock filters – Ads":

`||cdn.jsdelivr.net/*/detectIncognito$script`

Solution is to just don't use the CDN.
