### ISSUE TITLE
No detection on recent firefox

### ISSUE THREAD

**Issue by capocasa** [Joe12387/detectIncognito#36]
Chrome works fine, the demo on firefox gives no output:

![image](https://github.com/Joe12387/detectIncognito/assets/1167940/118745de-5fbf-4517-93f7-da41cfddb4dd)

**Comment by Joe12387** [comment]
The problem is not with Firefox, but rather because you have uBlock Origin installed. uBlock blocks the CDN from loading the library. Disabling uBlock or hosting the library from elsewhere resolves this.

**Comment by capocasa** [comment]
Thank you for clearing it up! Works fine without ublock.

![image](https://github.com/Joe12387/detectIncognito/assets/1167940/e4eb1e86-cefe-455f-b5e2-31d2fe48c428)
