### ISSUE TITLE
(0 , detectincognitojs__WEBPACK_IMPORTED_MODULE_11__.detectIncognito) is not a function

### ISSUE THREAD

**Issue by tanmayp22** [Joe12387/detectIncognito#37]
Got this issue
(0 , detectincognitojs__WEBPACK_IMPORTED_MODULE_11__.detectIncognito) is not a function

**Comment by karimtn** [comment]
in your package.json remove ths ^ and put "detectincognitojs": "1.3.0"

**Comment by Joe12387** [comment]
Yeah, I knew I'd fuck this up. If anyone has an idea what I did let me know. Downgrade to 1.3.0 in the meantime. Sorry!

**Comment by Joe12387** [comment]
Pushed 1.3.2, please verify the issue is resolved.

**Comment by jjwakn** [comment]
@Joe12387 I tried v1.3.2 today, is throwing the same error. v1.3.0 is working fine

**Comment by Joe12387** [comment]
Pushed v1.3.3. Let us know if anyone still has any issues.

**Comment by Joe12387** [comment]
Thanks to @panmenghan for the esm fix. v1.3.4 pushed to npm. Again, let us know if there are any other issues.

**Comment by karimtn** [comment]
Thanks @Joe12387 for the update.

**Comment by patotoma** [comment]
1.3.5 works great for me, thank you for work @Joe12387 
I think this issue can be closed now
