### ISSUE TITLE
Vivaldi always shows as isPrivate

### ISSUE THREAD

**Issue by desmond-F-allOtherDesmonds** [Joe12387/detectIncognito#40]
I use Vivaldi and it is a Major boon to my workflow, However, we need to stop incognito in browsers for most of our pages. Unfortunately this also throws Vivaldi users under the bus. We have tried several of the work-arounds that no longer work with the current version of Vivaldi. 

This is probably a know issue, but would appreciate feedback.

**Comment by Joe12387** [comment]
Hi. I'm unable to reproduce this issue, can you be more specific? Thanks.

<img width="1647" alt="Screenshot 2024-05-13 at 6 16 47 PM" src="https://github.com/Joe12387/detectIncognito/assets/489322/e7760cbb-66ca-403d-967b-0e60b93b124b">

**Comment by desmond-F-allOtherDesmonds** [comment]
It was the browser cache, i cleared for all time and it now is working. Sorry to waste your time.

**Comment by Joe12387** [comment]
No problem! Thanks for the report.

**Comment by desmond-F-allOtherDesmonds** [comment]
I am so sorry about this, After re-opening the window it came right back. I am on using Vivaldi 6.7.3329.29 (Stable channel) (64-bit) 
![image](https://github.com/Joe12387/detectIncognito/assets/169725058/28888543-4c11-4d5a-b751-16cb01e5de62)
clearing cache did not work this time. Also tried it on a diferent machine, first was intel win 10, second was AMD win 11 both coming up private, even though i have no private windows open.

**Comment by Joe12387** [comment]
If anyone else can find a way to reproduce the issue, please let me know.

**Comment by desmond-F-allOtherDesmonds** [comment]
I have tried a different profile, and there is no problem. I will compare/contrast my profile settings and see if I can isolate exactly what is causing this and report back.

**Comment by desmond-F-allOtherDesmonds** [comment]
I found it, I had cookies set to session only, thinking it just clears cookies after closing. 
![image](https://github.com/Joe12387/detectIncognito/assets/169725058/e65a5303-3f6a-455c-8662-3d0e7e970f01)

I guess it does this by making everything incognito. Sorry about any trouble this may have caused.

**Comment by Joe12387** [comment]
That makes sense, Tor Browser and Mullvad Browser do similar things to prevent sessions. Thanks for clearing things up, feel free to reopen this issue or create another if you find any other issues. Thanks!
