### ISSUE TITLE
After compiling with parcel: Error: detectIncognito cannot determine the browser

### ISSUE THREAD

**Issue by MarianoFacundoArch** [Joe12387/detectIncognito#44]
For some reason after new version, 
I get:
Error: detectIncognito cannot determine the browser

It was not happening in 1.3.5 . After updating, I get that error

**Comment by Joe12387** [comment]
Hi,

What device and browser are you using?

Joe

**Comment by MarianoFacundoArch** [comment]
I just created a pull request to get this updated. Is it possible to get it merged and release as a quickfix? Otherwise we cant update.

**Comment by Joe12387** [comment]
Thanks for the PR! Please confirm everything's working well for you?

**Comment by MarianoFacundoArch** [comment]
Perfectly working. Thank you for the speed of merging this ! :D
